version: '3'

name: twitter-oauth
services:
  app:
    restart: always
    build: .
    ports:
      - '9801:3333'
    environment:
      - DOPPLER_TOKEN=dp.st.prd.2DuQr8MXVHE8VFRDNlMW9LjsDhTIAPoAoigKgC376zG
